Numpy is the fundamental package for numeric computing with Python. It provides powerful ways to create,
store, and/or manipulate data, which makes it able to seamlessly and speedily integrate with a wide variety
of databases. This is also the foundation that Pandas is built on, which is a high-performance data-centric
package that we will learn later in the course.

In this lecture, we will talk about creating array with certain data types, manipulating array, selecting
elements from arrays, and loading dataset into array. Such functions are useful for manipulating data and
understanding the functionalities of other common Python data packages.

In [1]:
# You'll recall that we import a library using the `import` keyword as numpy's common abbreviation is np
import numpy as np # first import numpy module

In [2]:
np.__version__   # there are different version of numpy, it's good approach to be touch with latest update. (tip)

'1.16.2'

In [3]:
lis = [1,2,3,4,5,5,6,7,8,9]
_1dim = np.array(lis)
print('Array {0}, Type of array{1}'.format(_1dim,_1dim.dtype))

Array [1 2 3 4 5 5 6 7 8 9], Type of arrayint32


### Concept of Dimenstion in Array:
`there are a lot of dimension to be possible in array. we should only focus of mostly and oftenly use.`

In [4]:
# **Note** np.arange(include,exclude)
_1_dimention_array = np.array(np.arange(1,10))
_2_dimention_array = np.array(np.arange(1,11)).reshape(5,2)  # 5: row, 2 : column. 5*2 : 10
_3_dimention_array = np.array(np.arange(1,46)).reshape(5,3,3) # 5: row, 3: column, 3: Depth, 5*3*3 = 45
_4_dimention_array = np.array(np.arange(1,136)).reshape(5,3,3,3) #  row: 5, column: 3, Depth: 3, whole 3 dimentional array depth: 3
print(_1_dimention_array)
print(_2_dimention_array)
print(_3_dimention_array)
print(_4_dimention_array)

[1 2 3 4 5 6 7 8 9]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]]]
[[[[  1   2   3]
   [  4   5   6]
   [  7   8   9]]

  [[ 10  11  12]
   [ 13  14  15]
   [ 16  17  18]]

  [[ 19  20  21]
   [ 22  23  24]
   [ 25  26  27]]]


 [[[ 28  29  30]
   [ 31  32  33]
   [ 34  35  36]]

  [[ 37  38  39]
   [ 40  41  42]
   [ 43  44  45]]

  [[ 46  47  48]
   [ 49  50  51]
   [ 52  53  54]]]


 [[[ 55  56  57]
   [ 58  59  60]
   [ 61  62  63]]

  [[ 64  65  66]
   [ 67  68  69]
   [ 70  71  72]]

  [[ 73  74  75]
   [ 76  77  78]
   [ 79  80  81]]]


 [[[ 82  83  84]
   [ 85  86  87]
   [ 88  89  90]]

  [[ 91  92  93]
   [ 94  95  96]
   [ 97  98  99]]

  [[100 101 102]
   [103 104 105]
   [106 107 108]]]


 [[[109 110 111]
   [112 113 114]
   [115 116 117]]

  [[118 119 120]
   [121 122 123

In [5]:
print(_1_dimention_array.shape,_1_dimention_array.ndim)
print(_2_dimention_array.shape,_2_dimention_array.ndim)
print(_3_dimention_array.shape,_3_dimention_array.ndim)
print(_4_dimention_array.shape,_4_dimention_array.ndim)

(9,) 1
(5, 2) 2
(5, 3, 3) 3
(5, 3, 3, 3) 4


### Timing
Why we should use array? although it's answer is annoying, but it's true: python numpy library written in C language.   Numpy computational power must faster than normal python list.

In [6]:
%time lis = [2*i for i in range(1000000)]

Wall time: 386 ms


In [7]:
array = np.arange(1,1000000)
%time array*2

Wall time: 3.99 ms


array([      2,       4,       6, ..., 1999994, 1999996, 1999998])

### Array Creation Function

- asarray `Convert input to ndarray, but do not copy if the input is already an ndarray` &nbsp;
- arange `Like the built-in range but returns an ndarray instead of a list` &nbsp;
- ones `Produce an array of all 1s with the given shape and dtype` &nbsp;
- ones_like `Produce an array of all 1s with the given shape and dtype; ones_like takes another array and produces a ones array of the same shape and dtype` &nbsp;
- zeros `Like ones and ones_like but producing arrays of 0s instead` &nbsp;
- zeros_like `zero reference`
- empty `Create new arrays by allocating new memory, but do not populate with any values like ones and zeros` &nbsp; 
- empty_like `Above reference ` &nbsp;
- full : `Produce an array of the given shape and dtype with all values set to the indicated “fill value”` &nbsp
- full_like `Above reference`
- full_like ` takes another array and produces a filled array of the same shape and dtype`
- eye, identity `Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)`

#### Very interesting fact about numpy array. see example:

In [8]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
new_array = array[4:]
new_array

array([4, 5, 6, 7, 8, 9])

In [10]:
# ones and ones_like
one = np.ones((2,3))     # numpy.ones(shape, dtype=None, order='C')
print(one)
one_like = np.ones_like(np.arange(12))  # it can be convert multi dimentional value of vector into multidimentional value of 1's
print(one_like)            

[[1. 1. 1.]
 [1. 1. 1.]]
[1 1 1 1 1 1 1 1 1 1 1 1]


In [11]:
# Zero and Zero_like
zero = np.zeros((4,4))
print(zero)
zero_like = np.zeros_like(np.arange(1,17).reshape(4,4))
print(zero_like)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
# full and full like
# numpy.full(shape, fill_value, dtype=None, order='C')
full = np.full((2,2),np.inf)
print(full)
full_coustome = np.full((2,2),['a','b'])
print(full_coustome)


[[inf inf]
 [inf inf]]
[['a' 'b']
 ['a' 'b']]


In [13]:
# numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)
full_like = np.full_like(np.arange(6),1)
full_like
full_like2 = np.full_like(np.arange(6),0.4)
full_like


array([1, 1, 1, 1, 1, 1])

In [14]:
# eye or identity
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Arithmetic with Numpy Array
- Addition.
- Substraction.
- Division.
- Multiplication.
- Complex Number 


In [15]:
array1 = np.arange(1,17).reshape(4,4)
array2 = np.arange(1,17).reshape(4,4)
addition = array1 + array2
print('***** Addition********')
print(addition)
subtraction = array1 + array2
print('*****Subtraction********')
print(subtraction)
multiplication1 = array1*array2
print('*****Method 1: Multiplication********')
print(multiplication1)
multiplication2 = array1 @ array2
print('*****Method 2: Multiplication********')
print(multiplication2)
division = array1/array2
print('*****Division********')
print(division)


***** Addition********
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
*****Subtraction********
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
*****Method 1: Multiplication********
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]
*****Method 2: Multiplication********
[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]
*****Division********
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Slicing:
`What is Slicing? selecting inside elements from array. It may be single or multidimentional slicing.


In [16]:
# single dimention silicing.
arr = np.array(np.arange(1,10))
print(arr[:6]) 
print(arr[6:])

[1 2 3 4 5 6]
[7 8 9]


### important fact about numpy 

In [17]:
new_arr = arr[6:]
new_arr[:] = 0
print(arr)
print("As you noticed that we chnage only new array but it's result also reflect at old arr")

[1 2 3 4 5 6 0 0 0]
As you noticed that we chnage only new array but it's result also reflect at old arr


In [18]:
arr2 = np.array(np.arange(1,10))
copyarray = arr2[3:].copy()
copyarray[:] = 0
print(copyarray)
print(arr2)

[0 0 0 0 0 0]
[1 2 3 4 5 6 7 8 9]


In [19]:
# 2 dimentional slicing
_2array = np.array(np.arange(1,17).reshape(4,4))
print(_2array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
_2array[0][:]

array([1, 2, 3, 4])

In [21]:
 _3darr = np.array(np.arange(1,28).reshape(3,3,3))
 _3darr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [22]:
x = _3darr[0]
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
x[0]

array([1, 2, 3])

## Indexing Vs Slicing
index means in array (numpy array), starting position of zero and till nth location. &nbsp;
Slicing means break array into futher pieces.


### Indexing with Slices

In [24]:

# first dimention
arr[1:6]

array([2, 3, 4, 5, 6])

In [25]:
_2array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
_2array[:2]  # slicing at axis 0.

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
_2array[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [28]:
_2array[:,:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [29]:
_3darr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [30]:
x3 = _3darr[0]
x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Boolean Index

In [31]:
string_list = np.array(['a','b','c','d','e','f'])
numbers = np.random.rand(6,6)

In [32]:
print(string_list)
print(numbers)

['a' 'b' 'c' 'd' 'e' 'f']
[[0.03762245 0.54522178 0.02551724 0.59868818 0.34240408 0.85752182]
 [0.85948742 0.92996979 0.01594085 0.85355159 0.26211164 0.91172376]
 [0.43588122 0.53841202 0.40905933 0.309152   0.71088877 0.83549856]
 [0.8553929  0.09942158 0.46798852 0.19588041 0.7986551  0.00253846]
 [0.52692559 0.55343048 0.55593192 0.78418538 0.8887327  0.14936529]
 [0.2864753  0.51743121 0.31655    0.89755616 0.73943008 0.97202471]]


In [33]:
string_list == 'a'

array([ True, False, False, False, False, False])

In [34]:
numbers[string_list == 'a']

array([[0.03762245, 0.54522178, 0.02551724, 0.59868818, 0.34240408,
        0.85752182]])

In [35]:
numbers[string_list == 'a' ,1:4]

array([[0.54522178, 0.02551724, 0.59868818]])

In [36]:
numbers[string_list == 'a' ,1]

array([0.54522178])

In [37]:
numbers[string_list != 'a' ]

array([[0.85948742, 0.92996979, 0.01594085, 0.85355159, 0.26211164,
        0.91172376],
       [0.43588122, 0.53841202, 0.40905933, 0.309152  , 0.71088877,
        0.83549856],
       [0.8553929 , 0.09942158, 0.46798852, 0.19588041, 0.7986551 ,
        0.00253846],
       [0.52692559, 0.55343048, 0.55593192, 0.78418538, 0.8887327 ,
        0.14936529],
       [0.2864753 , 0.51743121, 0.31655   , 0.89755616, 0.73943008,
        0.97202471]])

In [38]:
invert = string_list == 'a'

In [39]:
invert

array([ True, False, False, False, False, False])

In [40]:
numbers[~invert]

array([[0.85948742, 0.92996979, 0.01594085, 0.85355159, 0.26211164,
        0.91172376],
       [0.43588122, 0.53841202, 0.40905933, 0.309152  , 0.71088877,
        0.83549856],
       [0.8553929 , 0.09942158, 0.46798852, 0.19588041, 0.7986551 ,
        0.00253846],
       [0.52692559, 0.55343048, 0.55593192, 0.78418538, 0.8887327 ,
        0.14936529],
       [0.2864753 , 0.51743121, 0.31655   , 0.89755616, 0.73943008,
        0.97202471]])

### Logical Operator or Bitwise opeartor
- instead of or (python) we use | (pipe symbol)
- instead of and (python) we use and (simple english word and)

In [41]:
bitwise = (string_list == 'a') | (string_list == 'b')
print(bitwise)

[ True  True False False False False]


In [42]:
numbers[bitwise]

array([[0.03762245, 0.54522178, 0.02551724, 0.59868818, 0.34240408,
        0.85752182],
       [0.85948742, 0.92996979, 0.01594085, 0.85355159, 0.26211164,
        0.91172376]])

In [43]:
numbers[numbers <= 0.3]

array([0.03762245, 0.02551724, 0.01594085, 0.26211164, 0.09942158,
       0.19588041, 0.00253846, 0.14936529, 0.2864753 ])

In [44]:
numbers[numbers <= 0.2] = 'NAN'

In [45]:
numbers

array([[       nan, 0.54522178,        nan, 0.59868818, 0.34240408,
        0.85752182],
       [0.85948742, 0.92996979,        nan, 0.85355159, 0.26211164,
        0.91172376],
       [0.43588122, 0.53841202, 0.40905933, 0.309152  , 0.71088877,
        0.83549856],
       [0.8553929 ,        nan, 0.46798852,        nan, 0.7986551 ,
               nan],
       [0.52692559, 0.55343048, 0.55593192, 0.78418538, 0.8887327 ,
               nan],
       [0.2864753 , 0.51743121, 0.31655   , 0.89755616, 0.73943008,
        0.97202471]])

In [46]:
numbers[string_list != 'a'] = 10
numbers


array([[        nan,  0.54522178,         nan,  0.59868818,  0.34240408,
         0.85752182],
       [10.        , 10.        , 10.        , 10.        , 10.        ,
        10.        ],
       [10.        , 10.        , 10.        , 10.        , 10.        ,
        10.        ],
       [10.        , 10.        , 10.        , 10.        , 10.        ,
        10.        ],
       [10.        , 10.        , 10.        , 10.        , 10.        ,
        10.        ],
       [10.        , 10.        , 10.        , 10.        , 10.        ,
        10.        ]])

# Fancy Indexing

In [47]:
np.random.randint(100,size=10)

array([55,  3, 25, 16, 15, 37, 25, 99, 66, 17])

In [48]:
fancyarry =  np.arange(10)

In [49]:
[fancyarry[4],fancyarry[2],fancyarry[0]]


[4, 2, 0]

In [50]:
fancyarry[[4,2,0]]

array([4, 2, 0])

In [51]:
fancyindex = np.empty((10,10))
for i in range(10):
    fancyindex[i] = i

In [52]:
fancyindex

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [53]:
fancyindex[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
fancyindex[[0,5]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [55]:
fancyindex2 = np.arange(16).reshape(4,4)
fancyindex2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
fancyindex2[[0,3],[1]]

array([ 1, 13])

In [57]:
fancyindex2[[0,2]][:,[1,0,3,2]]

array([[ 1,  0,  3,  2],
       [ 9,  8, 11, 10]])

In [58]:
# three dimentional
fancyindex3 = np.arange(27).reshape(3,3,3)
fancyindex3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [59]:
fancyindex3[[0,2,1],[0,1,0]]

array([[ 0,  1,  2],
       [21, 22, 23],
       [ 9, 10, 11]])