Numpy is the fundamental package for numeric computing with Python. It provides powerful ways to create,
store, and/or manipulate data, which makes it able to seamlessly and speedily integrate with a wide variety
of databases. This is also the foundation that Pandas is built on, which is a high-performance data-centric
package that we will learn later in the course.

In this lecture, we will talk about creating array with certain data types, manipulating array, selecting
elements from arrays, and loading dataset into array. Such functions are useful for manipulating data and
understanding the functionalities of other common Python data packages.

In [1]:
# You'll recall that we import a library using the `import` keyword as numpy's common abbreviation is np
import numpy as np # first import numpy module

In [2]:
np.__version__   # there are different version of numpy, it's good approach to be touch with latest update. (tip)

'1.16.2'

In [3]:
lis = [1,2,3,4,5,5,6,7,8,9]
_1dim = np.array(lis)
print('Array {0}, Type of array{1}'.format(_1dim,_1dim.dtype))

Array [1 2 3 4 5 5 6 7 8 9], Type of arrayint32


### Concept of Dimenstion in Array:
`there are a lot of dimension to be possible in array. we should only focus of mostly and oftenly use.`

In [4]:
# **Note** np.arange(include,exclude)
_1_dimention_array = np.array(np.arange(1,10))
_2_dimention_array = np.array(np.arange(1,11)).reshape(5,2)  # 5: row, 2 : column. 5*2 : 10
_3_dimention_array = np.array(np.arange(1,46)).reshape(5,3,3) # 5: row, 3: column, 3: Depth, 5*3*3 = 45
_4_dimention_array = np.array(np.arange(1,136)).reshape(5,3,3,3) #  row: 5, column: 3, Depth: 3, whole 3 dimentional array depth: 3
print(_1_dimention_array)
print(_2_dimention_array)
print(_3_dimention_array)
print(_4_dimention_array)

[1 2 3 4 5 6 7 8 9]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]]]
[[[[  1   2   3]
   [  4   5   6]
   [  7   8   9]]

  [[ 10  11  12]
   [ 13  14  15]
   [ 16  17  18]]

  [[ 19  20  21]
   [ 22  23  24]
   [ 25  26  27]]]


 [[[ 28  29  30]
   [ 31  32  33]
   [ 34  35  36]]

  [[ 37  38  39]
   [ 40  41  42]
   [ 43  44  45]]

  [[ 46  47  48]
   [ 49  50  51]
   [ 52  53  54]]]


 [[[ 55  56  57]
   [ 58  59  60]
   [ 61  62  63]]

  [[ 64  65  66]
   [ 67  68  69]
   [ 70  71  72]]

  [[ 73  74  75]
   [ 76  77  78]
   [ 79  80  81]]]


 [[[ 82  83  84]
   [ 85  86  87]
   [ 88  89  90]]

  [[ 91  92  93]
   [ 94  95  96]
   [ 97  98  99]]

  [[100 101 102]
   [103 104 105]
   [106 107 108]]]


 [[[109 110 111]
   [112 113 114]
   [115 116 117]]

  [[118 119 120]
   [121 122 123

In [5]:
print(_1_dimention_array.shape,_1_dimention_array.ndim)
print(_2_dimention_array.shape,_2_dimention_array.ndim)
print(_3_dimention_array.shape,_3_dimention_array.ndim)
print(_4_dimention_array.shape,_4_dimention_array.ndim)

(9,) 1
(5, 2) 2
(5, 3, 3) 3
(5, 3, 3, 3) 4


### Timing
Why we should use array? although it's answer is annoying, but it's true: python numpy library written in C language.   Numpy computational power must faster than normal python list.

In [6]:
%time lis = [2*i for i in range(1000000)]

Wall time: 320 ms


In [7]:
array = np.arange(1,1000000)
%time array*2

Wall time: 8.02 ms


array([      2,       4,       6, ..., 1999994, 1999996, 1999998])

### Array Creation Function

- asarray `Convert input to ndarray, but do not copy if the input is already an ndarray` &nbsp;
- arange `Like the built-in range but returns an ndarray instead of a list` &nbsp;
- ones `Produce an array of all 1s with the given shape and dtype` &nbsp;
- ones_like `Produce an array of all 1s with the given shape and dtype; ones_like takes another array and produces a ones array of the same shape and dtype` &nbsp;
- zeros `Like ones and ones_like but producing arrays of 0s instead` &nbsp;
- zeros_like `zero reference`
- empty `Create new arrays by allocating new memory, but do not populate with any values like ones and zeros` &nbsp; 
- empty_like `Above reference ` &nbsp;
- full : `Produce an array of the given shape and dtype with all values set to the indicated “fill value”` &nbsp
- full_like `Above reference`
- full_like ` takes another array and produces a filled array of the same shape and dtype`
- eye, identity `Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)`